<?php

/**
 * @file
 * Hooks for swiper library testing.
 */

use Drupal\Core\Site\Settings;

/**
 * Implements hook_library_info_alter().
 */
function swiper_library_test_library_info_alter(&$libraries, $extension) {
  if ($extension == 'swiper' and isset($libraries['swiper'])) {

    $paths = array_keys($libraries['swiper']['js']);
    $library_path = dirname($paths[0]);
    $library_path_test = '/' . Settings::get('file_public_path') . '/libraries/Swiper';

    // Set path to where the library was downloaded in the test environment.
    $js = \Drupal::config('swiper.settings')->get('swiper_debug') ?
      'swiper.jquery.js' : 'swiper.jquery.min.js';
    $libraries['swiper']['js'][$library_path_test . '/dist/js/' . $js] =
      $libraries['swiper']['js'][$library_path . '/' . $js];
    unset($libraries['swiper']['js'][$library_path . '/' . $js]);

    if (isset($libraries['swiper']['css']['component'][$library_path . '/swiper.min.css'])) {
      $libraries['swiper']['css']['component'][$library_path_test . '/dist/css/swiper.min.css'] =
        $libraries['swiper']['css']['component'][$library_path . '/swiper.min.css'];
      unset($libraries['swiper']['css']['component'][$library_path . '/swiper.min.css']);
    }

  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function swiper_library_test_page_attachments_alter(array &$attachments) {
  // Attach the swiper assets on the user page for testing.
  $current_path = \Drupal::service('path.current')->getPath();
  if (preg_match('|^\/?user\/\d+$|', $current_path)) {
    $swiper_attachments = swiper_add();
    $attachments['#attached']['library'] = array_merge(
      $attachments['#attached']['library'],
      $swiper_attachments['library']
    );
  }
}
