<?php

namespace Drupal\swiper;

/**
 * Class SwiperDefaults.
 *
 * Defines the default settings for this module.
 */
class SwiperDefaults {

  /**
   * Returns default swiper library options.
   */
  public static function defaultOptions() {
    return [
      // String Prefix string attached to the classes
      // of all elements generated by the plugin.
      'namespace' => 'swiper-',
      // Could be 'horizontal' or 'vertical' (for vertical slider).
      'direction' => 'horizontal',
      // Duration of transition between slides (in ms).
      'speed'     => 300,
      // @TODO add more options.
    ];
  }

}
